apiVersion: v1
kind: Service
metadata:
  annotations:
    app.openshift.io/vcs-ref: ""
    app.openshift.io/vcs-uri: https://github.com/DSpurway/RAG-with-Notebook
    openshift.io/generated-by: OpenShiftWebConsole
  labels:
    app: granite-llama-service
    app.kubernetes.io/component: granite-llama-service
    app.kubernetes.io/instance: granite-llama-service
    app.kubernetes.io/name: granite-llama-service
  name: granite-llama-service
  namespace: llm-on-techzone
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: granite-llama-service
    deployment: granite-llama-service
  sessionAffinity: None
  type: ClusterIP

# Made with Bob
